### PR TITLE
DOCSP-43308-toc-refactor

### PR DESCRIPTION
**Pull request by ltran-mdb2**
## DESCRIPTION

Refactoring the ToC with the following guidelines: https://www.mongodb.com/docs/meta/style-guide/style/toc-labels/

## STAGING

https://deploy-preview-357--docs-mongodb-shell.netlify.app

## JIRA

https://jira.mongodb.org/browse/DOCSP-43308

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Is this free of spelling errors?
- [x] Is this free of grammatical errors?
- [x] Is this free of staging / rendering issues?
- [x] Are all the links working?

## External Review Requirements

[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)

### CODE REVIEW

**Review by jmd-mongo — COMMENTED** [review]
Thanks for these helpful updates, @ltran-mdb2! This one LGTM from a content standpoint.

I notice the [most recent build errored](https://app.netlify.com/sites/docs-mongodb-shell/deploys/66f5a11d020b7c0008b8db22). Could you re-run a build when you get a chance? 

Thank you!
Joe

**Comment by ltran-mdb2** [comment]
I checked in with #ask-docs-platform and they said the buildhooks error should not impact production (is some Netlify experimentation that is going on) @jmd-mongo !

**Review by jmd-mongo — APPROVED** [review]
Thanks, @ltran-mdb2! This one LGTM!

**Comment by ltran-mdb2** [comment]
Hi @sarahemlin ! Could you review this docs PR that refactors the mongosh repo ToC?

**Review by sarahemlin — APPROVED** [review]

**Pull request merged**
