### PR TITLE
DOCSP-32212-parsing-logic

### PR DESCRIPTION
**Pull request by jason-price-mongodb**
## DESCRIPTION

Boolean logic updates for connection strings. Also fixed an unrelated minor formatting issue in the binary constructor output.

## STAGING

https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-32212-parsing-logic/changelog/#v2.0.0

https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-32212-parsing-logic/connect/#limitations

## JIRA

https://jira.mongodb.org/browse/DOCSP-32212

## BUILD LOG

https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64e6a04f57e37806c5b493f9

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Is this free of spelling errors?
- [ ] Is this free of grammatical errors?
- [ ] Is this free of staging / rendering issues?
- [ ] Are all the links working?

## External Review Requirements

[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)

### CODE REVIEW

**Comment by jason-price-mongodb** [comment]
@sarah-olson-mongodb please review. Thanks!

**Review by sarah-olson-mongodb — APPROVED** [review]
Thanks @jason-price-mongodb! LGTM

**Comment by jason-price-mongodb** [comment]
@addaleax please review. Cheers.
@GaurabAryal CC'ing you on PR. Cheers.

**Review by addaleax — APPROVED** [review]

**Comment by addaleax** [comment]
Similarly here, I think this one is good to merge.

**Pull request merged**
