### PR TITLE
DOCSP-31754-release-notes

### PR DESCRIPTION
**Pull request by jason-price-mongodb**
## DESCRIPTION

Add link to release notes in Jira per Anna's link.

## STAGING

https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-31754-release-notes/changelog/#v2.0.0

## JIRA

https://jira.mongodb.org/browse/DOCSP-31754

## BUILD LOG

https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64ef8e4524fcc731b4e5688a

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Is this free of spelling errors?
- [ ] Is this free of grammatical errors?
- [ ] Is this free of staging / rendering issues?
- [ ] Are all the links working?

## External Review Requirements

[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)

### CODE REVIEW

**Comment by jason-price-mongodb** [comment]
@sarah-olson-mongodb @addaleax please review.
@GaurabAryal CC'ing.

**Review by jmd-mongo — CHANGES_REQUESTED** [review]
Thanks for the update here, @jason-price-mongodb! 

I think we also generally include the full output of the [Release Notes generator](https://jira.mongodb.org/secure/ReleaseNote.jspa?version=36482&styleName=Text&projectId=17381&Create=Create&atl_token=ASGJ-NC06-6R0X-EKH7_50f0519a4b9c2916ab59a42a15b2ed4f1cd525d4_lin) here as well. 

Could you add this? 

Thanks,
Joe

**Comment by addaleax** [comment]
@jmd-mongo I don’t see any places where we’ve done this in the past, and technically there might still be minor changes to the list generated by JIRA between now and the 2.0.0 release date.

**Comment by jason-price-mongodb** [comment]
@jmd-mongo The existing changelog for the shell only has links to the release notes, and am following the existing pattern for this. Cheers.

**Review by jmd-mongo — APPROVED** [review]
Thanks, @jason-price-mongodb. This one LGTM!

Thanks,
Joe

**Review by addaleax — APPROVED** [review]

**Pull request merged**
